# Generated by Django 5.1.5 on 2025-01-30 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FromOurKitchen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeorders',
            name='category',
        ),
    ]
